name: fennec_aaa
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        run: |
          export PACKAGE_NAME='fennec_aaa'
          sudo apt update
          sudo apt install git unzip wget -y
          cd ~
          git clone --depth 1 https://gitlab.com/fdroid/fdroiddata.git
          cd fdroiddata
          rm config.yml
          touch config.yml
          cd metadata
          export VERCODE=$(awk -F': *' '/^[[:space:]]*CurrentVersionCode:/ {print $2}' org.mozilla.fennec_fdroid.yml)
          export COMMIT=$(cat org.mozilla.fennec_fdroid.yml | grep -E '[[:space:]]*commit:' | tail -1 | sed -E 's/.*commit:[[:space:]]*([^[:space:]]+).*/\1/')
          export NDK=$(cat org.mozilla.fennec_fdroid.yml | grep -E '[[:space:]]*ndk:' | tail -1 | sed -E 's/.*ndk:[[:space:]]*([^[:space:]]+).*/\1/')
          sed -i "s/fennec_fdroid/$PACKAGE_NAME/" org.mozilla.fennec_fdroid.yml
          sed -i 's/    prebuild: \.\/prebuild.sh \$\$VERSION\$\$ \$\$VERCODE\$\$/    prebuild: git reset --hard \$COMMIT \&\& git grep -l "fennec_fdroid" -- \. \| xargs perl -pi -e "s\/fennec_fdroid\/\$PACKAGE_NAME\/g" \&\& git add \. \&\& git commit --amend -m override_package_name \&\& \.\/prebuild.sh \$\$VERSION\$\$ \$\$VERCODE\$\$/' org.mozilla.fennec_fdroid.yml
          mv org.mozilla.fennec_fdroid.yml "org.mozilla.$PACKAGE_NAME.yml"
          mv org.mozilla.fennec_fdroid "org.mozilla.$PACKAGE_NAME"
          cd ~
          wget --tries=100 --retry-connrefused --waitretry=5 -O studio.html https://developer.android.com/studio
          export CMDLINETOOLS="$(awk '/<table class="download">/ { count++ }
          count >= 2 {
            if (match($0, /commandlinetools-linux-.*zip/)) {
              print substr($0, RSTART, RLENGTH)
              exit
            }
          }' studio.html)"
          rm studio.html
          wget --tries=100 --retry-connrefused --waitretry=5 "https://dl.google.com/android/repository/${CMDLINETOOLS}"
          unzip "$CMDLINETOOLS"
          mkdir -p ~/Android/Sdk/cmdline-tools/latest
          mv cmdline-tools/* ~/Android/Sdk/cmdline-tools/latest
          rm -r cmdline-tools
          cd ~/Android/Sdk/cmdline-tools/latest/bin
          echo y | ./sdkmanager "platform-tools" "ndk;$NDK"
          cd ~/fdroiddata
          docker run --rm -v $HOME/Android/Sdk:/opt/android-sdk -v $(pwd):/repo -e ANDROID_HOME:/opt/android-sdk registry.gitlab.com/fdroid/docker-executable-fdroidserver:master build "$PACKAGE_NAME:$VERCODE" -v
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fennec_fork_apks
          path: |
            ~/fdroiddata/build/srclib/MozFennec/obj/gradle/build/mobile/android/fenix/app/outputs/apk/release/app-*-release-unsigned.apk
